dist: bionic
language: python
python:
  - 3.6
  - 3.7
addons:
  postgresql: "9.3"
  apt:
    packages:
      - postgresql-9.3-postgis-2.4
install:
  - pip install -U pip
  - pip install -i https://pypi.pacificclimate.org/simple/ -r requirements.txt -r test_requirements.txt
  - pip install -i https://pypi.pacificclimate.org/simple/ .
script: py.test -v
