version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
    formatter: default
  file:
    class: logging.FileHandler
    level: DEBUG
    filename: sdpb.log
    formatter: default

loggers:
  sdpb:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  sqlalchemy.engine:
    level: WARNING
    handlers: [console, file]
    propagate: no

root:
  level: DEBUG
  handlers: [console,file]