services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: sdpb-local:latest
    container_name: station-data-portal-backend
    user: "1001:1001"
    env_file:
      - ../.env
      - gunicorn.env
    volumes:
      - type: bind
        source: ./gunicorn.conf
        target: /app/gunicorn.conf
        read_only: true
      - type: bind
        source: ./logging.conf
        target: /app/logging.conf
        read_only: true
      - type: bind
        source: ../.pgpass
        target: /workspaces/station-data-portal-backend/.pgpass
        read_only: true
    ports:
      - "8000:8000"
