name: Pypi Publishing

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Poetry
      run: |
        pip install poetry==1.8.5

    - name: Install, build and publish project
      env:
        PCIC_PYPI_USERNAME: ${{ secrets.pcic_at_pypi_username }}
        PCIC_PYPI_PASSWORD: ${{ secrets.pcic_at_pypi_password }}
      run: |
        # Configure Poetry to publish to PCIC private package repository
        # Private repo name is "pcic". We could factor that out as an env var...
        poetry config repositories.pcic https://pypi.pacificclimate.org/
        poetry config http-basic.pcic $PCIC_PYPI_USERNAME $PCIC_PYPI_PASSWORD
        
        # Install, build and publish
        poetry install
        poetry build
        poetry publish -r pcic
